spring: 
  profiles:
    active: dev
--- 
server:
  port: 8001
spring: 
   profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource        
    url: jdbc:mysql://132.232.59.22:3306/cloudDB01?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true      #数据库连接地址
    username: root
    password: 61154852a
    dbcp2:
      min-idle: 5                                      
      initial-size: 5                                  
      max-total: 5                                     
      max-wait-millis: 200                             
    driver-class-name: com.mysql.cj.jdbc.Driver        
  cloud:
    config:
      enabled: false
eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001 
    prefer-ip-address: true    
info:  
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring: 
   profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource        
    url: jdbc:mysql://132.232.59.22:3306/cloudDB02?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true      #数据库连接地址
    username: root
    password: 61154852a
    dbcp2:
      min-idle: 5                                       
      initial-size: 5                                  
      max-total: 5                                      
      max-wait-millis: 200                             
    driver-class-name: com.mysql.cj.jdbc.Driver         
  cloud:
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001 
    prefer-ip-address: true     
info: 
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
